"""
backend/docgen.py
PDF report generation for LY‑Type1 regulatory submissions.

Uses fpdf2 when available; falls back to a minimal raw‑bytes PDF stub
so the download link always works even without fpdf2 installed.
"""

from __future__ import annotations
import datetime


def create_report(data: dict) -> bytes:
    """Generate a simple PDF regulatory report from a data dict.

    Parameters
    ----------
    data : dict
        Arbitrary key/value payload (e.g. title, compound, risk_score …)

    Returns
    -------
    bytes  — valid PDF content
    """
    try:
        return _fpdf_report(data)
    except ImportError:
        return _raw_pdf_stub(data)


def _fpdf_report(data: dict) -> bytes:
    """Build a styled PDF using fpdf2."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Header ────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_fill_color(30, 60, 114)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 14, "LY‑Type1  ·  Regulatory AI Report", ln=True, fill=True, align="C")
    pdf.ln(4)

    # ── Metadata line ─────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 100, 100)
    now = datetime.datetime.utcnow().strftime("%Y‑%m‑%d %H:%M UTC")
    pdf.cell(0, 6, f"Generated: {now}   |   Compliance: ICH M7 / FDA Elsa 4.0", ln=True)
    pdf.ln(3)

    # ── Section: Report fields ────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(30, 60, 114)
    pdf.cell(0, 8, "Assessment Summary", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    pdf.set_font("Helvetica", size=11)
    pdf.set_text_color(30, 30, 30)

    for key, val in data.items():
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(55, 8, str(key).replace("_", " ").title() + ":", ln=False)
        pdf.set_font("Helvetica", size=11)
        pdf.multi_cell(0, 8, str(val))

    pdf.ln(6)

    # ── Disclaimer ────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0, 5,
        "DISCLAIMER: This report is generated by an AI decision‑support system "
        "and must be reviewed by a qualified regulatory scientist before submission. "
        "LY‑Type1 is not an approved regulatory authority tool."
    )

    return bytes(pdf.output())


def _raw_pdf_stub(data: dict) -> bytes:
    """Return a minimal hand‑crafted PDF that embeds the report data."""
    lines = [f"{k}: {v}" for k, v in data.items()]
    body = " | ".join(lines)

    # Minimal PDF 1.4 with a single‑page text stream
    stream = f"BT /F1 10 Tf 40 750 Td (LY-Type1 Report) Tj 0 -20 Td ({body[:200]}) Tj ET"
    stream_bytes = stream.encode("latin-1", errors="replace")
    length = len(stream_bytes)

    pdf = (
        f"%PDF-1.4\n"
        f"1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n"
        f"2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj\n"
        f"3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R"
        f"/Resources<</Font<</F1 4 0 R>>>>>>/Contents 5 0 R>>endobj\n"
        f"4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n"
        f"5 0 obj<</Length {length}>>\nstream\n"
    ).encode("latin-1")

    end = b"\nendstream\nendobj\n"
    xref_pos = len(pdf) + length + len(end)
    trailer = (
        f"xref\n0 6\n"
        f"0000000000 65535 f\n"
        f"0000000009 00000 n\n"
        f"0000000058 00000 n\n"
        f"0000000115 00000 n\n"
        f"0000000266 00000 n\n"
        f"0000000332 00000 n\n"
        f"trailer<</Size 6/Root 1 0 R>>\n"
        f"startxref\n{xref_pos}\n%%EOF"
    ).encode("latin-1")

    return pdf + stream_bytes + end + trailer
